### ISSUE TITLE
The new stream namelist format is not working as expected for HAFS ERA5 data mode

### ISSUE THREAD

**Issue by uturuncoglu** [NOAA-EMC/CDEPS#32]
I am trying to update the existing HAFS data atmosphere (ERA5) configuration that was using XML format to define the stream data files to the new ESMF config format (datm.streams) but I have an issue with it and it seems that CDEPS is not  reading input files correctly. Following is my stream namelist file, which I generated based on the file under `tests/parm/datm.streams.IN`,

```
stream_info:               ERA5_HOURLY01
taxmode01:                 limit 
mapalgo01:                 bilinear
tInterpAlgo01:             linear
readMode01:                single
dtlimit01:                 1.5
stream_offset01:           0
yearFirst01:               2019
yearLast01:                2019
yearAlign01:               2019
stream_vectors01:          "u:v"
stream_mesh_file01:        "INPUT/TL639_200618_ESMFmesh.nc" 
stream_lev_dimname01:      null
stream_data_files01:       "INPUT/ERA5.TL639.2019.08.200618_subset.nc" "INPUT/ERA5.TL639.2019.09.200618_subset.nc"
stream_data_variables01:   "u10 Sa_u" "v10 Sa_v" "t2m Sa_tbot" "skt Sa_tskn" "d2m Sa_tdew" "msl Sa_pslv" "sp Sa_pbot" "skt Sa_tskn" "d2m Sa_tdew" "msl Sa_pslv" "sp Sa_pbot" "tp Faxa_rain" "cp Faxa_rainc" "lsp Faxa_rainl" "csf Faxa_snowc" "lsf Faxa_snowl" "ssrd Faxa_swdn" "ssr Faxa_swnet" "strd Faxa_lwdn" "str Faxa_lwnet" "aluvp Faxa_swvdr" "aluvd Faxa_swvdf" "alnip Faxa_swndf" "alnid Faxa_swndf" "sshf Faxa_sen" "slhf Faxa_lat" "ewss Faxa_taux" "nsss Faxa_tauy"
```

I also tried to use single file in `stream_data_files01` but the result is same. At this point I am not sure about the source of the problem and all the fields are full of zero when I try to write out mediator history file. The CDEPS log also does not show anything related with the reading the data, which I had in XML version of the configuration. @binli2337 do you see any issue with the configuration file?

**Comment by uturuncoglu** [comment]
Maybe this is just a build issue because it seems that CDEPS does not enter to `shr_stream_init_from_esmfconfig` call. The model used in HAFS fork has following last commit

```
commit 8613d7a8a4722857354e3be5b6068b096c6f8523
Author: Bin Liu <bin.liu@noaa.gov>
Date:   Wed May 26 22:31:45 2021 +0000

    Update submodule FV3, which has the parameter variables rlmx and elmx (maximum
    allowed mixing length and dissipation mixing length in the GFS scale-aware TKE
    EDMF PBL scheme) as namelist options.
```

Is there any bug fix related with CDEPS or known issue after this commit?

**Comment by uturuncoglu** [comment]
If so, we might need to sync HAFS fork.

**Comment by binli2337** [comment]
@uturuncoglu The stream namelist file looks good.

**Comment by uturuncoglu** [comment]
@binli2337 Thanks. I could run DATM configuration now after reverting back a patch that combines CDEPS libraries. I think we could close this issue. I could reopen it if I need help. Thanks again.
