### ISSUE TITLE
CDEPS time logic is flawed for GEFS forcing files

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/CDEPS#38]
I see that the time coming out of the model is not consistent with the time-stamp in the netcdf files for the GEFS forcing files.  

If you look at the log files from the regression tests, the cfsr forcing test works correctly:

(shr_strdata_readstrm) reading file lb: DATM_INPUT/cfsr.201110.nc       1
(shr_strdata_readstrm) reading file ub: DATM_INPUT/cfsr.201110.nc       2

but the GEFS forcing shows:

(shr_strdata_readstrm) reading file lb: DATM_INPUT/gefs.201110.nc      21
(shr_strdata_readstrm) reading file ub: DATM_INPUT/gefs.201110.nc       1

I believe this is because of a possible calendar bug, the GEFS files have a time unit of:
time:units = "hours since 1-1-1 00:00:00" ;
                time:calendar = "gregorian" ;
                
I put in a bunch of print statements, and the figuring out out of times is not returning the correct dates.
please see on hera: /scratch2/BMC/gsienkf/Philip.Pegion/stmp2/Philip.Pegion/FV3_RT/rt_86678/datm_cdeps_control_gefs/out.5

**Comment by binli2337** [comment]
@hyunchul386 I have regenerated the GEFS input data used in the current ufs-weather-model regression tests (from 2011100100 to 2011100600).

**Comment by hyunchul386** [comment]
@BinLi The GEFS_DATM has been updated for the time stamp issue,
and the updated GEFS_DATM can be found at HPSS,
/5year/NCEPDEV/marineda/DATM_INPUT/GEFS_new/
Let me know if there are any issues for the data

**Comment by binli** [comment]
> [binli2337](/binli2337)

[binli2337](https://github.com/binli2337)

**Comment by binli2337** [comment]
The issue is fixed.
