### ISSUE TITLE
CFSR and GEFS input files need to be reprocessed

### ISSUE THREAD

**Issue by binli2337** [NOAA-EMC/CDEPS#6]
The current CFSR and GEFS input netcdf files are not CF-1.0 compliant in the time axis.  Since the time axis information is used in CDEPS for time interpolation, it is necessary to reprocess the netcdf files to be CF-1.0 compliant.

Right now, one forcing file is provided for each time level for both CFSR and GEFS data sources. Since these input files need to be listed in the input xml files, it would be better to convert multiple input files into a single file. For example, it would be better if we have one file for each month for both CFSR and GEFS data sources.

**Comment by DeniseWorthen** [comment]
This can be done using NCO and the record concatenating function. For example, to combine all Aug 2000 files into a single file:  ncrcat  cfsr.200008*nc cfsr.200008.nc

**Comment by binli2337** [comment]
The issue is fixed. New GEFS data files have been generated.
